name: Build and Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Producing the static files
  build:
    runs-on: ubuntu-latest
    env:
      SERVER_PREFIX: "/apoc-gardens-wiki/"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print environment variable
        run: echo "Domain prefix is $DOMAIN_PREFIX"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Start script
        run: npm run start
        
      - name: Rename files with invalid characters
        run: |
          find ./public -name "*:*" | while read file; do
            mv "$file" "$(echo $file | tr ':' '_')"
          done

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: .

  deploy:
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
  
      # Step 2: Ensure CNAME file exists
      - name: Create CNAME file
        run: |
          echo "lanka.wiki.apoc-gardens" > ./CNAME
  
      # Step 3: Commit the CNAME file (optional, if not already in repo)
      - name: Commit and push CNAME
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add CNAME
          git commit -m "Add CNAME for GitHub Pages"
          git push
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public # Path should match where your built files are extracted

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
